version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd
    volumes:
      - ${MONGO_HOST_DATA}:/data/db
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: "redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  back:
    container_name: back
    image: worker-project-backend
    build:
      dockerfile: ./projects/front/Dockerfile
    environment:
      - NODE_ENV=development
      - APP_SERVER=1.0.0
      - APPLICATION_NAME=boilerplate
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=p@ssw0rd
      - MONGO_DATABASE=workers
      - MONGO_USERS_DATABASE=workers
      - MONGO_USERS_COLLECTION=users
      - MONGO_ROLES_DATABASE=workers
      - MONGO_ROLES_COLLECTION=roles
      - MONGO_PROJECTS_DATABASE=workers
      - MONGO_PROJECTS_COLLECTION=projects
      - MONGO_SPECIALIZATIONS_DATABASE=workers
      - MONGO_SPECIALIZATIONS_COLLECTION=specializations
      - JWT_TOKEN_SECRET=SECRETTOKENJWT
      - JWT_EXPIRES_IN_MINUTES=30
      - REDIS_READ_URL=redis://redis:6379
      - REDIS_WRITE_URL=redis://redis:6379
    ports:
      - "5000:5000"

  front:
    image: worker-project-frontend
    build:
      dockerfile: ./projects/front/Dockerfile
    container_name: front
    ports:
      - "3000:3000"
