version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=p@ssw0rd
    volumes:
      - ${MONGO_HOST_DATA}:/data/db
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: "redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
