// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i
	 */
	HI: string
	projects: {
		/**
		 * P​R​O​J​E​C​T​S
		 */
		tittle: string
	}
	errors: {
		/**
		 * E​r​r​o​r​ ​1
		 */
		'001': string
		/**
		 * E​r​r​o​r​ ​2
		 */
		'002': string
	}
}

export type TranslationFunctions = {
	/**
	 * Hi
	 */
	HI: () => LocalizedString
	projects: {
		/**
		 * PROJECTS
		 */
		tittle: () => LocalizedString
	}
	errors: {
		/**
		 * Error 1
		 */
		'001': () => LocalizedString
		/**
		 * Error 2
		 */
		'002': () => LocalizedString
	}
}

export type Formatters = {}
